const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('api', {
  startupRetry: () => ipcRenderer.invoke('startup:retry'),
  startupWaitForBackend: () => ipcRenderer.invoke('startup:waitForBackend'),
  startupUiReady: (payload: Record<string, unknown>) => ipcRenderer.invoke('startup:uiReady', payload),
  startupUiFailed: (payload: Record<string, unknown>) => ipcRenderer.invoke('startup:uiFailed', payload),
  captureLiquidBackdrop: (size?: { width?: number; height?: number }) => ipcRenderer.invoke('glass:captureBackdrop', size),
  onStartupStatus: (callback: (payload: Record<string, unknown>) => void) => {
    ipcRenderer.on('startup:status', (_event: unknown, payload: Record<string, unknown>) => callback(payload));
  },
  sendMessage: (message: string | Record<string, unknown>, target?: string | Record<string, unknown>) => ipcRenderer.invoke('agent:send', message, target),
  enqueueGuide: (envelope: Record<string, unknown>) => ipcRenderer.invoke('agent:enqueueGuide', envelope),
  queueAction: (action: string, input: Record<string, unknown>, target: string | Record<string, unknown>) => ipcRenderer.invoke('agent:queueAction', action, input, target),
  checkpointConversation: (request: Record<string, unknown>) => ipcRenderer.invoke('agent:checkpointConversation', request),
  compressContext: (request: Record<string, unknown>) => ipcRenderer.invoke('agent:compressContext', request),
  rateAutoRoute: (request: Record<string, unknown>) => ipcRenderer.invoke('agent:rateAutoRoute', request),
  stopConversation: (request: Record<string, unknown>) => ipcRenderer.invoke('agent:stopConversation', request),
  setWorkRunExpanded: (request: Record<string, unknown>) => ipcRenderer.invoke('agent:setWorkRunExpanded', request),
  sendPrompt: (message: string, _model?: string) => ipcRenderer.invoke('agent:sendPrompt', message),
  setMode: (mode: string) => ipcRenderer.invoke('agent:setMode', mode),
  setModel: (model: string) => ipcRenderer.invoke('agent:setModel', model),
  setIntelligence: (tier: string) => ipcRenderer.invoke('agent:setIntelligence', tier),
  setInputMode: (mode: string, target?: string | Record<string, unknown>) => ipcRenderer.invoke('agent:setInputMode', mode, target),
  setConversation: (id: string) => ipcRenderer.invoke('agent:setConversation', id),
  activateConversation: (target: string | Record<string, unknown>) => ipcRenderer.invoke('agent:activateConversation', target),
  updateGoal: (goal: string, target?: string | Record<string, unknown>) => ipcRenderer.invoke('agent:updateGoal', goal, target),
  toggleGoalPause: (target?: string | Record<string, unknown>) => ipcRenderer.invoke('agent:toggleGoalPause', target),
  clearGoal: (target?: string | Record<string, unknown>) => ipcRenderer.invoke('agent:clearGoal', target),
  ensureConversation: (target: string | Record<string, unknown>) => ipcRenderer.invoke('agent:ensureConversation', target),
  getState: (target?: string | Record<string, unknown>) => ipcRenderer.invoke('agent:getState', target),
  getConversationDraft: (conversationId?: string) => ipcRenderer.invoke('conversation:getDraft', conversationId),
  saveConversationDraft: (conversationId: string, draft: string | null) => ipcRenderer.invoke('conversation:saveDraft', conversationId, draft),
  getConversationPlan: (conversationId?: string) => ipcRenderer.invoke('agent:getConversationPlan', conversationId),
  updateConversationPlan: (plan: Record<string, unknown>, conversationId?: string) => ipcRenderer.invoke('agent:updateConversationPlan', plan, conversationId),
  setConversationPinned: (id: string, pinned: boolean) => ipcRenderer.invoke('agent:setConversationPinned', id, pinned),
  setConversationBranchCommunication: (target: string | Record<string, unknown>, enabled: boolean) => ipcRenderer.invoke('agent:setConversationBranchCommunication', target, enabled),
  renameConversation: (id: string, title: string) => ipcRenderer.invoke('agent:renameConversation', id, title),
  reorderConversations: (ids: string[]) => ipcRenderer.invoke('agent:reorderConversations', ids),
  browserRegisterGuest: (guestContentsId: number, target?: Record<string, unknown>) => ipcRenderer.invoke('browser:registerGuest', guestContentsId, target),
  onBrowserEnsureGuest: (callback: (target?: Record<string, unknown>) => void) => {
    ipcRenderer.on('browser:ensureGuest', (_event: unknown, target?: Record<string, unknown>) => callback(target));
  },
  onKeyboardCommand: (callback: (payload: Record<string, unknown>) => void) => {
    ipcRenderer.on('keyboard:command', (_event: unknown, payload: Record<string, unknown>) => callback(payload));
  },
  browserControl: (request: Record<string, unknown>) => ipcRenderer.invoke('browser:control', request),
  computerUseState: (target?: Record<string, unknown>) => ipcRenderer.invoke('agent:computerUseState', target),
  setComputerUseEnabled: (target: Record<string, unknown>, enabled: boolean) => ipcRenderer.invoke('agent:setComputerUseEnabled', target, enabled),
  runFlow: (name: string, input?: string, start?: number) => ipcRenderer.invoke('flow:run', name, input, start),
  resumeFlow: (response: string, target?: string | Record<string, unknown>) => ipcRenderer.invoke('flow:resume', response, target),
  guideFlow: (message: string, target?: string | Record<string, unknown>) => ipcRenderer.invoke('flow:guide', message, target),
  stopFlow: (target?: string | Record<string, unknown>) => ipcRenderer.invoke('flow:stop', target),
  saveConfig: (cfg: string | Record<string, unknown>) => ipcRenderer.invoke('agent:saveConfig', cfg),
  openGlobalConfig: () => ipcRenderer.invoke('agent:openGlobalConfig'),
  reloadGlobalConfig: () => ipcRenderer.invoke('agent:reloadGlobalConfig'),
  readGlobalPrompt: () => ipcRenderer.invoke('agent:readGlobalPrompt'),
  saveGlobalPrompt: (content: string) => ipcRenderer.invoke('agent:saveGlobalPrompt', content),
  abortConversation: (target?: string | Record<string, unknown>) => ipcRenderer.invoke('agent:abortConversation', target),
  rewindConversation: (target: string | Record<string, unknown>, messageIndex: number) => ipcRenderer.invoke('agent:rewindConversation', target, messageIndex),
  branchConversation: (target: string | Record<string, unknown>, messageIndex: number, text: string, locator?: Record<string, unknown>) => ipcRenderer.invoke('agent:branchConversation', target, messageIndex, text, locator),
  inspectConversationBranch: (target: string | Record<string, unknown>, branchId: string, branchGroupId?: string) => ipcRenderer.invoke('agent:inspectConversationBranch', target, branchId, branchGroupId),
  activateConversationBranch: (target: string | Record<string, unknown>, branchId: string, branchGroupId?: string) => ipcRenderer.invoke('agent:activateConversationBranch', target, branchId, branchGroupId),
  archive: (target?: string | Record<string, unknown>) => ipcRenderer.invoke('agent:archive', target),
  listArchives: (scope?: string) => ipcRenderer.invoke('agent:listArchives', scope),
  deleteArchive: (name: string) => ipcRenderer.invoke('agent:deleteArchive', name),
  readArchive: (name: string) => ipcRenderer.invoke('agent:readArchive', name),
  restoreArchive: (name: string) => ipcRenderer.invoke('agent:restoreArchive', name),
  openWorkspaceFile: (path: string) => ipcRenderer.invoke('agent:openWorkspaceFile', path),
  saveWorkspaceFile: (token: string, content: string, expectedRevision: string) => ipcRenderer.invoke('agent:saveWorkspaceFile', token, content, expectedRevision),
  closeWorkspaceFile: (token: string) => ipcRenderer.invoke('agent:closeWorkspaceFile', token),
  closeWorkspacePreview: (token: string) => ipcRenderer.invoke('agent:closeWorkspacePreview', token),
  confirmEditorClose: (language: string, filePath: string) => ipcRenderer.invoke('agent:confirmEditorClose', language, filePath),
  loadEarlierConversationMessages: (target: string | Record<string, unknown>) => ipcRenderer.invoke('conversation:loadEarlier', target),
  listFlows: () => ipcRenderer.invoke('flow:list'),
  readFlow: (name: string) => ipcRenderer.invoke('flow:read', name),
  saveFlow: (workflow: Record<string, unknown>) => ipcRenderer.invoke('flow:save', workflow),
  readWorkspacePrompt: () => ipcRenderer.invoke('workspace:readPrompt'),
  saveWorkspacePrompt: (content: string) => ipcRenderer.invoke('workspace:savePrompt', content),
  editorComplete: (request: Record<string, unknown>) => ipcRenderer.invoke('agent:editorComplete', request),
  editorCompleteCancel: () => ipcRenderer.invoke('agent:editorCompleteCancel'),
  onEditorCompletionDelta: (callback: (payload: Record<string, unknown>) => void) => {
    ipcRenderer.on('agent:editorCompletionDelta', (_event: unknown, payload: Record<string, unknown>) => callback(payload));
  },
  editorAssist: (request: Record<string, unknown>) => ipcRenderer.invoke('agent:editorAssist', request),
  filePathForFile: (file: File) => {
    try {
      return webUtils && file ? webUtils.getPathForFile(file) : '';
    } catch {
      return '';
    }
  },
  getFileTree: (dir?: string) => ipcRenderer.invoke('agent:getFileTree', dir),
  selectFolder: () => ipcRenderer.invoke('dialog:selectFolder'),
  executeBash: (cmd: string, shell: string, cwd: string) => ipcRenderer.invoke('agent:executeBash', cmd, shell, cwd),
  openExternal: (path: string) => ipcRenderer.invoke('agent:openExternal', path),
  openWebUrl: (url: string) => ipcRenderer.invoke('app:openWebUrl', url),
  selectWorkspace: (id: string) => ipcRenderer.invoke('agent:selectWorkspace', id),
  createWorkspace: (name?: string) => ipcRenderer.invoke('agent:createWorkspace', name),
  createExternalWorkspace: (name: string, dirPath: string) => ipcRenderer.invoke('agent:createExternalWorkspace', name, dirPath),
  listSshConnections: () => ipcRenderer.invoke('ssh:listConnections'),
  saveSshConnection: (input: Record<string, unknown>) => ipcRenderer.invoke('ssh:saveConnection', input),
  deleteSshConnection: (id: string) => ipcRenderer.invoke('ssh:deleteConnection', id),
  validateSshConnection: (id: string, remoteRoot?: string) => ipcRenderer.invoke('ssh:validateConnection', id, remoteRoot),
  createSshWorkspace: (input: Record<string, unknown>) => ipcRenderer.invoke('ssh:createWorkspace', input),
  deleteWorkspace: (name: string) => ipcRenderer.invoke('agent:deleteWorkspace', name),
  setWorkspacePinned: (id: string, pinned: boolean) => ipcRenderer.invoke('agent:setWorkspacePinned', id, pinned),
  saveSetting: (section: string, key: string, value: unknown) => ipcRenderer.invoke('agent:saveSetting', section, key, value),
  setProviderEnabled: (providerId: string, enabled: boolean) => ipcRenderer.invoke('agent:setProviderEnabled', providerId, enabled),
  validateModels: (selected?: string[]) => ipcRenderer.invoke('agent:validateModels', selected),
  modelValidationStatus: () => ipcRenderer.invoke('agent:modelValidationStatus'),
  fuzzyInject: (name: string, url: string, key: string, protocol?: string) => ipcRenderer.invoke('agent:fuzzyInject', name, url, key, protocol),
  githubCopilotLogin: () => ipcRenderer.invoke('github:copilotLogin'),
  listSkills: () => ipcRenderer.invoke('skills:list'),
  marketSkills: () => ipcRenderer.invoke('skills:market'),
  marketSkillSources: () => ipcRenderer.invoke('skills:marketSources'),
  addSkillMarketSource: (input: Record<string, unknown>) => ipcRenderer.invoke('skills:addMarketSource', input),
  removeSkillMarketSource: (idOrName: string) => ipcRenderer.invoke('skills:removeMarketSource', idOrName),
  setSkillMarketSourceEnabled: (idOrName: string, enabled: boolean) => ipcRenderer.invoke('skills:setMarketSourceEnabled', idOrName, enabled),
  downloadSkill: (name: string, url: string) => ipcRenderer.invoke('skills:download', name, url),
  installLocalSkill: (sourceDir: string, targetName?: string) => ipcRenderer.invoke('skills:installLocal', sourceDir, targetName),
  setSkillEnabled: (name: string, enabled: boolean) => ipcRenderer.invoke('skills:setEnabled', name, enabled),
  removeSkill: (name: string) => ipcRenderer.invoke('skills:remove', name),
  refreshSkills: () => ipcRenderer.invoke('skills:refresh'),
  listMcpServers: () => ipcRenderer.invoke('mcp:list'),
  discoverDshCompatibility: () => ipcRenderer.invoke('dsh:discover'),
  installDshBundle: (manifestPath: string) => ipcRenderer.invoke('dsh:installBundle', manifestPath),
  uninstallDshBundle: (name: string) => ipcRenderer.invoke('dsh:uninstallBundle', name),
  setDshBundleEnabled: (name: string, enabled: boolean) => ipcRenderer.invoke('dsh:setBundleEnabled', name, enabled),
  upsertMcpServer: (input: Record<string, unknown>) => ipcRenderer.invoke('mcp:upsert', input),
  setMcpServerEnabled: (id: string, enabled: boolean) => ipcRenderer.invoke('mcp:setEnabled', id, enabled),
  removeMcpServer: (id: string) => ipcRenderer.invoke('mcp:remove', id),
  memoryLabRead: (selector?: string) => ipcRenderer.invoke('memoryLab:read', selector),
  memoryLabVisualization: () => ipcRenderer.invoke('memoryLab:visualization'),
  openImageViewer: (request: Record<string, unknown>) => ipcRenderer.invoke('viewer:open', request),
  openMemoryOverview: () => ipcRenderer.invoke('viewer:openMemoryOverview'),
  memoryLabUpdate: (input: Record<string, unknown>) => ipcRenderer.invoke('memoryLab:update', input),
  memoryLabReindex: () => ipcRenderer.invoke('memoryLab:reindex'),
  updateVersion: () => ipcRenderer.invoke('update:version'),
  mobilePairingQr: () => ipcRenderer.invoke('mobile:pairingQr'),
  mobilePairingStatus: () => ipcRenderer.invoke('mobile:pairingStatus'),
  mobileServerStatus: () => ipcRenderer.invoke('mobile:serverStatus'),
  setRemoteTouchEnabled: (enabled: boolean) => ipcRenderer.invoke('mobile:setRemoteTouchEnabled', enabled),
  updateCheckGithub: (input: Record<string, unknown>) => ipcRenderer.invoke('update:checkGithub', input),
  updateApplyGithub: (input: Record<string, unknown>) => ipcRenderer.invoke('update:applyGithub', input),
  updateInstallLocal: (input: Record<string, unknown>) => ipcRenderer.invoke('update:installLocal', input),
  gh: (argv: string[]) => ipcRenderer.invoke('github:gh', argv),
  githubOverview: (repo?: string) => ipcRenderer.invoke('github:overview', repo),
  listAutomations: () => ipcRenderer.invoke('automation:list'),
  createAutomation: (item: Record<string, unknown>) => ipcRenderer.invoke('automation:create', item),
  toggleAutomation: (id: string) => ipcRenderer.invoke('automation:toggle', id),
  deleteAutomation: (id: string) => ipcRenderer.invoke('automation:delete', id),
  automationWakeStatus: () => ipcRenderer.invoke('automation:wakeStatus'),
  minimize: () => ipcRenderer.invoke('app:minimize'),
  maximize: () => ipcRenderer.invoke('app:maximize'),
  close: () => ipcRenderer.invoke('app:close'),
  lifecycleState: () => ipcRenderer.invoke('app:lifecycleState'),
  exitApplication: () => ipcRenderer.invoke('app:exit'),
  sidecarStatus: () => ipcRenderer.invoke('sidecar:status'),
  sidecarRestart: () => ipcRenderer.invoke('sidecar:restart'),
  // Native PTY Terminal
  terminalSpawn: (shell: string) => ipcRenderer.invoke('pty:spawn', shell),
  terminalWrite: (sessionId: string, data: string) => ipcRenderer.invoke('pty:write', sessionId, data),
  terminalKill: (sessionId: string, timeoutMs?: number) => ipcRenderer.invoke('pty:kill', sessionId, timeoutMs),
  terminalGetBuffer: (sessionId: string) => ipcRenderer.invoke('pty:getBuffer', sessionId),
  terminalTakeoverState: (conversationId?: string, actorId?: string) => ipcRenderer.invoke('agentTerminal:takeoverState', conversationId, actorId),
  terminalTakeoverWrite: (sessionId: string, data: string, conversationId?: string, actorId?: string) => ipcRenderer.invoke('agentTerminal:takeoverWrite', sessionId, data, conversationId, actorId),
  terminalTakeoverResize: (sessionId: string, cols: number, rows: number, conversationId?: string, actorId?: string) => ipcRenderer.invoke('agentTerminal:takeoverResize', sessionId, cols, rows, conversationId, actorId),
  terminalTakeoverStop: (sessionId: string, conversationId?: string, actorId?: string) => ipcRenderer.invoke('agentTerminal:takeoverStop', sessionId, conversationId, actorId),
  terminalTakeoverDetach: (sessionId: string, conversationId?: string, actorId?: string) => ipcRenderer.invoke('agentTerminal:takeoverDetach', sessionId, conversationId, actorId),
  wslBackendStatus: () => ipcRenderer.invoke('wsl:backendStatus'),
  wslBackendTest: () => ipcRenderer.invoke('wsl:backendTest'),
  onTerminalData: (callback: (event: unknown, sessionId: string, data: string) => void) => {
    ipcRenderer.on('pty:data', callback);
  },
  onTerminalExit: (callback: (event: unknown, sessionId: string, code: number) => void) => {
    ipcRenderer.on('pty:exit', callback);
  },
  onTerminalTakeover: (callback: (event: unknown, payload: unknown) => void) => {
    ipcRenderer.on('agentTerminal:takeover', callback);
  },
  removeTerminalDataListener: () => {
    ipcRenderer.removeAllListeners('pty:data');
  },
  removeTerminalTakeoverListener: () => {
    ipcRenderer.removeAllListeners('agentTerminal:takeover');
  },
  onAutomationUpdated: (callback: () => void) => {
    ipcRenderer.on('automation:updated', callback);
  },
  onAgentWorkEvent: (callback: (event: unknown, payload: unknown) => void) => {
    ipcRenderer.on('agent:workEvent', callback);
  },
  onWorkspaceChanged: (callback: (payload: Record<string, unknown>) => void) => {
    ipcRenderer.on('workspace:changed', (_event: unknown, payload: Record<string, unknown>) => callback(payload));
  },
  removeWorkspaceChangedListener: () => {
    ipcRenderer.removeAllListeners('workspace:changed');
  },
  removeAgentWorkEventListener: () => {
    ipcRenderer.removeAllListeners('agent:workEvent');
  },
});
